[package]
name = "user-story-jj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.3", features = ["derive"] }
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
